/**
 * Comprehensive World Countries & Primary Time Zones Catalog
 * Contains 230+ countries and territories with standard ISO codes, IANA timezones, and display labels.
 */

const ALL_COUNTRIES = [
  { name: "Afghanistan", code: "AF", tz: "Asia/Kabul", label: "AFT (UTC+4:30)" },
  { name: "Albania", code: "AL", tz: "Europe/Tirane", label: "CET/CEST (UTC+1/+2)" },
  { name: "Algeria", code: "DZ", tz: "Africa/Algiers", label: "CET (UTC+1)" },
  { name: "American Samoa", code: "AS", tz: "Pacific/Pago_Pago", label: "SST (UTC-11)" },
  { name: "Andorra", code: "AD", tz: "Europe/Andorra", label: "CET/CEST (UTC+1/+2)" },
  { name: "Angola", code: "AO", tz: "Africa/Luanda", label: "WAT (UTC+1)" },
  { name: "Anguilla", code: "AI", tz: "America/Anguilla", label: "AST (UTC-4)" },
  { name: "Antigua and Barbuda", code: "AG", tz: "America/Antigua", label: "AST (UTC-4)" },
  { name: "Argentina", code: "AR", tz: "America/Argentina/Buenos_Aires", label: "ART (UTC-3)" },
  { name: "Armenia", code: "AM", tz: "Asia/Yerevan", label: "AMT (UTC+4)" },
  { name: "Aruba", code: "AW", tz: "America/Aruba", label: "AST (UTC-4)" },
  { name: "Australia", code: "AU", tz: "Australia/Sydney", label: "AEST/AEDT (UTC+10/+11)" },
  { name: "Austria", code: "AT", tz: "Europe/Vienna", label: "CET/CEST (UTC+1/+2)" },
  { name: "Azerbaijan", code: "AZ", tz: "Asia/Baku", label: "AZT (UTC+4)" },
  { name: "Bahamas", code: "BS", tz: "America/Nassau", label: "EDT/EST (UTC-4/-5)" },
  { name: "Bahrain", code: "BH", tz: "Asia/Bahrain", label: "AST (UTC+3)" },
  { name: "Bangladesh", code: "BD", tz: "Asia/Dhaka", label: "BST (UTC+6)" },
  { name: "Barbados", code: "BB", tz: "America/Barbados", label: "AST (UTC-4)" },
  { name: "Belarus", code: "BY", tz: "Europe/Minsk", label: "MSK (UTC+3)" },
  { name: "Belgium", code: "BE", tz: "Europe/Brussels", label: "CET/CEST (UTC+1/+2)" },
  { name: "Belize", code: "BZ", tz: "America/Belize", label: "CST (UTC-6)" },
  { name: "Benin", code: "BJ", tz: "Africa/Porto-Novo", label: "WAT (UTC+1)" },
  { name: "Bermuda", code: "BM", tz: "Atlantic/Bermuda", label: "AST/ADT (UTC-4/-3)" },
  { name: "Bhutan", code: "BT", tz: "Asia/Thimphu", label: "BTT (UTC+6)" },
  { name: "Bolivia", code: "BO", tz: "America/La_Paz", label: "BOT (UTC-4)" },
  { name: "Bosnia and Herzegovina", code: "BA", tz: "Europe/Sarajevo", label: "CET/CEST (UTC+1/+2)" },
  { name: "Botswana", code: "BW", tz: "Africa/Gaborone", label: "CAT (UTC+2)" },
  { name: "Brazil", code: "BR", tz: "America/Sao_Paulo", label: "BRT (UTC-3)" },
  { name: "British Virgin Islands", code: "VG", tz: "America/Tortola", label: "AST (UTC-4)" },
  { name: "Brunei", code: "BN", tz: "Asia/Brunei", label: "BNT (UTC+8)" },
  { name: "Bulgaria", code: "BG", tz: "Europe/Sofia", label: "EET/EEST (UTC+2/+3)" },
  { name: "Burkina Faso", code: "BF", tz: "Africa/Ouagadougou", label: "GMT (UTC+0)" },
  { name: "Burundi", code: "BI", tz: "Africa/Bujumbura", label: "CAT (UTC+2)" },
  { name: "Cabo Verde", code: "CV", tz: "Atlantic/Cape_Verde", label: "CVT (UTC-1)" },
  { name: "Cambodia", code: "KH", tz: "Asia/Phnom_Penh", label: "ICT (UTC+7)" },
  { name: "Cameroon", code: "CM", tz: "Africa/Douala", label: "WAT (UTC+1)" },
  { name: "Canada", code: "CA", tz: "America/Toronto", label: "EDT/EST (UTC-4/-5)" },
  { name: "Cayman Islands", code: "KY", tz: "America/Cayman", label: "EST (UTC-5)" },
  { name: "Central African Republic", code: "CF", tz: "Africa/Bangui", label: "WAT (UTC+1)" },
  { name: "Chad", code: "TD", tz: "Africa/Ndjamena", label: "WAT (UTC+1)" },
  { name: "Chile", code: "CL", tz: "America/Santiago", label: "CLT/CLST (UTC-4/-3)" },
  { name: "China", code: "CN", tz: "Asia/Shanghai", label: "CST (UTC+8)" },
  { name: "Colombia", code: "CO", tz: "America/Bogota", label: "COT (UTC-5)" },
  { name: "Comoros", code: "KM", tz: "Indian/Comoro", label: "EAT (UTC+3)" },
  { name: "Congo (Brazzaville)", code: "CG", tz: "Africa/Brazzaville", label: "WAT (UTC+1)" },
  { name: "Congo (Kinshasa)", code: "CD", tz: "Africa/Kinshasa", label: "WAT (UTC+1)" },
  { name: "Cook Islands", code: "CK", tz: "Pacific/Rarotonga", label: "CKT (UTC-10)" },
  { name: "Costa Rica", code: "CR", tz: "America/Costa_Rica", label: "CST (UTC-6)" },
  { name: "Croatia", code: "HR", tz: "Europe/Zagreb", label: "CET/CEST (UTC+1/+2)" },
  { name: "Cuba", code: "CU", tz: "America/Havana", label: "CST/CDT (UTC-5/-4)" },
  { name: "Curacao", code: "CW", tz: "America/Curacao", label: "AST (UTC-4)" },
  { name: "Cyprus", code: "CY", tz: "Asia/Nicosia", label: "EET/EEST (UTC+2/+3)" },
  { name: "Czech Republic", code: "CZ", tz: "Europe/Prague", label: "CET/CEST (UTC+1/+2)" },
  { name: "Denmark", code: "DK", tz: "Europe/Copenhagen", label: "CET/CEST (UTC+1/+2)" },
  { name: "Djibouti", code: "DJ", tz: "Africa/Djibouti", label: "EAT (UTC+3)" },
  { name: "Dominica", code: "DM", tz: "America/Dominica", label: "AST (UTC-4)" },
  { name: "Dominican Republic", code: "DO", tz: "America/Santo_Domingo", label: "AST (UTC-4)" },
  { name: "Ecuador", code: "EC", tz: "America/Guayaquil", label: "ECT (UTC-5)" },
  { name: "Egypt", code: "EG", tz: "Africa/Cairo", label: "EET/EEST (UTC+2/+3)" },
  { name: "El Salvador", code: "SV", tz: "America/El_Salvador", label: "CST (UTC-6)" },
  { name: "Equatorial Guinea", code: "GQ", tz: "Africa/Malabo", label: "WAT (UTC+1)" },
  { name: "Eritrea", code: "ER", tz: "Africa/Asmara", label: "EAT (UTC+3)" },
  { name: "Estonia", code: "EE", tz: "Europe/Tallinn", label: "EET/EEST (UTC+2/+3)" },
  { name: "Eswatini", code: "SZ", tz: "Africa/Mbabane", label: "SAST (UTC+2)" },
  { name: "Ethiopia", code: "ET", tz: "Africa/Addis_Ababa", label: "EAT (UTC+3)" },
  { name: "Falkland Islands", code: "FK", tz: "Atlantic/Stanley", label: "FKST (UTC-3)" },
  { name: "Faroe Islands", code: "FO", tz: "Atlantic/Faroe", label: "WET/WEST (UTC+0/+1)" },
  { name: "Fiji", code: "FJ", tz: "Pacific/Fiji", label: "FJT (UTC+12)" },
  { name: "Finland", code: "FI", tz: "Europe/Helsinki", label: "EET/EEST (UTC+2/+3)" },
  { name: "France", code: "FR", tz: "Europe/Paris", label: "CET/CEST (UTC+1/+2)" },
  { name: "French Guiana", code: "GF", tz: "America/Cayenne", label: "GFT (UTC-3)" },
  { name: "French Polynesia", code: "PF", tz: "Pacific/Tahiti", label: "TAHT (UTC-10)" },
  { name: "Gabon", code: "GA", tz: "Africa/Libreville", label: "WAT (UTC+1)" },
  { name: "Gambia", code: "GM", tz: "Africa/Banjul", label: "GMT (UTC+0)" },
  { name: "Georgia", code: "GE", tz: "Asia/Tbilisi", label: "GET (UTC+4)" },
  { name: "Germany", code: "DE", tz: "Europe/Berlin", label: "CET/CEST (UTC+1/+2)" },
  { name: "Ghana", code: "GH", tz: "Africa/Accra", label: "GMT (UTC+0)" },
  { name: "Gibraltar", code: "GI", tz: "Europe/Gibraltar", label: "CET/CEST (UTC+1/+2)" },
  { name: "Greece", code: "GR", tz: "Europe/Athens", label: "EET/EEST (UTC+2/+3)" },
  { name: "Greenland", code: "GL", tz: "America/Nuuk", label: "WGT (UTC-2)" },
  { name: "Grenada", code: "GD", tz: "America/Grenada", label: "AST (UTC-4)" },
  { name: "Guadeloupe", code: "GP", tz: "America/Guadeloupe", label: "AST (UTC-4)" },
  { name: "Guam", code: "GU", tz: "Pacific/Guam", label: "ChST (UTC+10)" },
  { name: "Guatemala", code: "GT", tz: "America/Guatemala", label: "CST (UTC-6)" },
  { name: "Guernsey", code: "GG", tz: "Europe/Guernsey", label: "GMT/BST (UTC+0/+1)" },
  { name: "Guinea", code: "GN", tz: "Africa/Conakry", label: "GMT (UTC+0)" },
  { name: "Guinea-Bissau", code: "GW", tz: "Africa/Bissau", label: "GMT (UTC+0)" },
  { name: "Guyana", code: "GY", tz: "America/Guyana", label: "GYT (UTC-4)" },
  { name: "Haiti", code: "HT", tz: "America/Port-au-Prince", label: "EST/EDT (UTC-5/-4)" },
  { name: "Honduras", code: "HN", tz: "America/Tegucigalpa", label: "CST (UTC-6)" },
  { name: "Hong Kong", code: "HK", tz: "Asia/Hong_Kong", label: "HKT (UTC+8)" },
  { name: "Hungary", code: "HU", tz: "Europe/Budapest", label: "CET/CEST (UTC+1/+2)" },
  { name: "Iceland", code: "IS", tz: "Atlantic/Reykjavik", label: "GMT (UTC+0)" },
  { name: "India", code: "IN", tz: "Asia/Kolkata", label: "IST (UTC+5:30)" },
  { name: "Indonesia", code: "ID", tz: "Asia/Jakarta", label: "WIB (UTC+7)" },
  { name: "Iran", code: "IR", tz: "Asia/Tehran", label: "IRST (UTC+3:30)" },
  { name: "Iraq", code: "IQ", tz: "Asia/Baghdad", label: "AST (UTC+3)" },
  { name: "Ireland", code: "IE", tz: "Europe/Dublin", label: "IST/GMT (UTC+1/+0)" },
  { name: "Isle of Man", code: "IM", tz: "Europe/Isle_of_Man", label: "GMT/BST (UTC+0/+1)" },
  { name: "Israel", code: "IL", tz: "Asia/Jerusalem", label: "IST/IDT (UTC+2/+3)" },
  { name: "Italy", code: "IT", tz: "Europe/Rome", label: "CET/CEST (UTC+1/+2)" },
  { name: "Ivory Coast (Cote d'Ivoire)", code: "CI", tz: "Africa/Abidjan", label: "GMT (UTC+0)" },
  { name: "Jamaica", code: "JM", tz: "America/Jamaica", label: "EST (UTC-5)" },
  { name: "Japan", code: "JP", tz: "Asia/Tokyo", label: "JST (UTC+9)" },
  { name: "Jersey", code: "JE", tz: "Europe/Jersey", label: "GMT/BST (UTC+0/+1)" },
  { name: "Jordan", code: "JO", tz: "Asia/Amman", label: "AST (UTC+3)" },
  { name: "Kazakhstan", code: "KZ", tz: "Asia/Almaty", label: "ALMT (UTC+5)" },
  { name: "Kenya", code: "KE", tz: "Africa/Nairobi", label: "EAT (UTC+3)" },
  { name: "Kiribati", code: "KI", tz: "Pacific/Tarawa", label: "GILT (UTC+12)" },
  { name: "Kosovo", code: "XK", tz: "Europe/Belgrade", label: "CET/CEST (UTC+1/+2)" },
  { name: "Kuwait", code: "KW", tz: "Asia/Kuwait", label: "AST (UTC+3)" },
  { name: "Kyrgyzstan", code: "KG", tz: "Asia/Bishkek", label: "KGT (UTC+6)" },
  { name: "Laos", code: "LA", tz: "Asia/Vientiane", label: "ICT (UTC+7)" },
  { name: "Latvia", code: "LV", tz: "Europe/Riga", label: "EET/EEST (UTC+2/+3)" },
  { name: "Lebanon", code: "LB", tz: "Asia/Beirut", label: "EET/EEST (UTC+2/+3)" },
  { name: "Lesotho", code: "LS", tz: "Africa/Maseru", label: "SAST (UTC+2)" },
  { name: "Liberia", code: "LR", tz: "Africa/Monrovia", label: "GMT (UTC+0)" },
  { name: "Libya", code: "LY", tz: "Africa/Tripoli", label: "EET (UTC+2)" },
  { name: "Liechtenstein", code: "LI", tz: "Europe/Vaduz", label: "CET/CEST (UTC+1/+2)" },
  { name: "Lithuania", code: "LT", tz: "Europe/Vilnius", label: "EET/EEST (UTC+2/+3)" },
  { name: "Luxembourg", code: "LU", tz: "Europe/Luxembourg", label: "CET/CEST (UTC+1/+2)" },
  { name: "Macao", code: "MO", tz: "Asia/Macau", label: "CST (UTC+8)" },
  { name: "Madagascar", code: "MG", tz: "Indian/Antananarivo", label: "EAT (UTC+3)" },
  { name: "Malawi", code: "MW", tz: "Africa/Blantyre", label: "CAT (UTC+2)" },
  { name: "Malaysia", code: "MY", tz: "Asia/Kuala_Lumpur", label: "MYT (UTC+8)" },
  { name: "Maldives", code: "MV", tz: "Indian/Maldives", label: "MVT (UTC+5)" },
  { name: "Mali", code: "ML", tz: "Africa/Bamako", label: "GMT (UTC+0)" },
  { name: "Malta", code: "MT", tz: "Europe/Malta", label: "CET/CEST (UTC+1/+2)" },
  { name: "Marshall Islands", code: "MH", tz: "Pacific/Majuro", label: "MHT (UTC+12)" },
  { name: "Martinique", code: "MQ", tz: "America/Martinique", label: "AST (UTC-4)" },
  { name: "Mauritania", code: "MR", tz: "Africa/Nouakchott", label: "GMT (UTC+0)" },
  { name: "Mauritius", code: "MU", tz: "Indian/Mauritius", label: "MUT (UTC+4)" },
  { name: "Mayotte", code: "YT", tz: "Indian/Mayotte", label: "EAT (UTC+3)" },
  { name: "Mexico", code: "MX", tz: "America/Mexico_City", label: "CST (UTC-6)" },
  { name: "Micronesia", code: "FM", tz: "Pacific/Pohnpei", label: "PONT (UTC+11)" },
  { name: "Moldova", code: "MD", tz: "Europe/Chisinau", label: "EET/EEST (UTC+2/+3)" },
  { name: "Monaco", code: "MC", tz: "Europe/Monaco", label: "CET/CEST (UTC+1/+2)" },
  { name: "Mongolia", code: "MN", tz: "Asia/Ulaanbaatar", label: "ULAT (UTC+8)" },
  { name: "Montenegro", code: "ME", tz: "Europe/Podgorica", label: "CET/CEST (UTC+1/+2)" },
  { name: "Montserrat", code: "MS", tz: "America/Montserrat", label: "AST (UTC-4)" },
  { name: "Morocco", code: "MA", tz: "Africa/Casablanca", label: "WEST/WET (UTC+1/+0)" },
  { name: "Mozambique", code: "MZ", tz: "Africa/Maputo", label: "CAT (UTC+2)" },
  { name: "Myanmar (Burma)", code: "MM", tz: "Asia/Yangon", label: "MMT (UTC+6:30)" },
  { name: "Namibia", code: "NA", tz: "Africa/Windhoek", label: "CAT (UTC+2)" },
  { name: "Nauru", code: "NR", tz: "Pacific/Nauru", label: "NRT (UTC+12)" },
  { name: "Nepal", code: "NP", tz: "Asia/Kathmandu", label: "NPT (UTC+5:45)" },
  { name: "Netherlands", code: "NL", tz: "Europe/Amsterdam", label: "CET/CEST (UTC+1/+2)" },
  { name: "New Caledonia", code: "NC", tz: "Pacific/Noumea", label: "NCT (UTC+11)" },
  { name: "New Zealand", code: "NZ", tz: "Pacific/Auckland", label: "NZST/NZDT (UTC+12/+13)" },
  { name: "Nicaragua", code: "NI", tz: "America/Managua", label: "CST (UTC-6)" },
  { name: "Niger", code: "NE", tz: "Africa/Niamey", label: "WAT (UTC+1)" },
  { name: "Nigeria", code: "NG", tz: "Africa/Lagos", label: "WAT (UTC+1)" },
  { name: "Niue", code: "NU", tz: "Pacific/Niue", label: "NUT (UTC-11)" },
  { name: "North Korea", code: "KP", tz: "Asia/Pyongyang", label: "KST (UTC+9)" },
  { name: "North Macedonia", code: "MK", tz: "Europe/Skopje", label: "CET/CEST (UTC+1/+2)" },
  { name: "Northern Mariana Islands", code: "MP", tz: "Pacific/Saipan", label: "ChST (UTC+10)" },
  { name: "Norway", code: "NO", tz: "Europe/Oslo", label: "CET/CEST (UTC+1/+2)" },
  { name: "Oman", code: "OM", tz: "Asia/Muscat", label: "GST (UTC+4)" },
  { name: "Pakistan", code: "PK", tz: "Asia/Karachi", label: "PKT (UTC+5)" },
  { name: "Palau", code: "PW", tz: "Pacific/Palau", label: "PWT (UTC+9)" },
  { name: "Palestine", code: "PS", tz: "Asia/Gaza", label: "EET/EEST (UTC+2/+3)" },
  { name: "Panama", code: "PA", tz: "America/Panama", label: "EST (UTC-5)" },
  { name: "Papua New Guinea", code: "PG", tz: "Pacific/Port_Moresby", label: "PGT (UTC+10)" },
  { name: "Paraguay", code: "PY", tz: "America/Asuncion", label: "PYT/PYST (UTC-4/-3)" },
  { name: "Peru", code: "PE", tz: "America/Lima", label: "PET (UTC-5)" },
  { name: "Philippines", code: "PH", tz: "Asia/Manila", label: "PHT (UTC+8)" },
  { name: "Poland", code: "PL", tz: "Europe/Warsaw", label: "CET/CEST (UTC+1/+2)" },
  { name: "Portugal", code: "PT", tz: "Europe/Lisbon", label: "WET/WEST (UTC+0/+1)" },
  { name: "Puerto Rico", code: "PR", tz: "America/Puerto_Rico", label: "AST (UTC-4)" },
  { name: "Qatar", code: "QA", tz: "Asia/Qatar", label: "AST (UTC+3)" },
  { name: "Reunion", code: "RE", tz: "Indian/Reunion", label: "RET (UTC+4)" },
  { name: "Romania", code: "RO", tz: "Europe/Bucharest", label: "EET/EEST (UTC+2/+3)" },
  { name: "Russia", code: "RU", tz: "Europe/Moscow", label: "MSK (UTC+3)" },
  { name: "Rwanda", code: "RW", tz: "Africa/Kigali", label: "CAT (UTC+2)" },
  { name: "Saint Helena", code: "SH", tz: "Atlantic/St_Helena", label: "GMT (UTC+0)" },
  { name: "Saint Kitts and Nevis", code: "KN", tz: "America/St_Kitts", label: "AST (UTC-4)" },
  { name: "Saint Lucia", code: "LC", tz: "America/St_Lucia", label: "AST (UTC-4)" },
  { name: "Saint Martin", code: "MF", tz: "America/Marigot", label: "AST (UTC-4)" },
  { name: "Saint Vincent and the Grenadines", code: "VC", tz: "America/St_Vincent", label: "AST (UTC-4)" },
  { name: "Samoa", code: "WS", tz: "Pacific/Apia", label: "WST (UTC+13)" },
  { name: "San Marino", code: "SM", tz: "Europe/San_Marino", label: "CET/CEST (UTC+1/+2)" },
  { name: "Sao Tome and Principe", code: "ST", tz: "Africa/Sao_Tome", label: "GMT (UTC+0)" },
  { name: "Saudi Arabia", code: "SA", tz: "Asia/Riyadh", label: "AST (UTC+3)" },
  { name: "Senegal", code: "SN", tz: "Africa/Dakar", label: "GMT (UTC+0)" },
  { name: "Serbia", code: "RS", tz: "Europe/Belgrade", label: "CET/CEST (UTC+1/+2)" },
  { name: "Seychelles", code: "SC", tz: "Indian/Mahe", label: "SCT (UTC+4)" },
  { name: "Sierra Leone", code: "SL", tz: "Africa/Freetown", label: "GMT (UTC+0)" },
  { name: "Singapore", code: "SG", tz: "Asia/Singapore", label: "SGT (UTC+8)" },
  { name: "Sint Maarten", code: "SX", tz: "America/Lower_Princes", label: "AST (UTC-4)" },
  { name: "Slovakia", code: "SK", tz: "Europe/Bratislava", label: "CET/CEST (UTC+1/+2)" },
  { name: "Slovenia", code: "SI", tz: "Europe/Ljubljana", label: "CET/CEST (UTC+1/+2)" },
  { name: "Solomon Islands", code: "SB", tz: "Pacific/Guadalcanal", label: "SBT (UTC+11)" },
  { name: "Somalia", code: "SO", tz: "Africa/Mogadishu", label: "EAT (UTC+3)" },
  { name: "South Africa", code: "ZA", tz: "Africa/Johannesburg", label: "SAST (UTC+2)" },
  { name: "South Korea", code: "KR", tz: "Asia/Seoul", label: "KST (UTC+9)" },
  { name: "South Sudan", code: "SS", tz: "Africa/Juba", label: "CAT (UTC+2)" },
  { name: "Spain", code: "ES", tz: "Europe/Madrid", label: "CET/CEST (UTC+1/+2)" },
  { name: "Sri Lanka", code: "LK", tz: "Asia/Colombo", label: "IST (UTC+5:30)" },
  { name: "Sudan", code: "SD", tz: "Africa/Khartoum", label: "CAT (UTC+2)" },
  { name: "Suriname", code: "SR", tz: "America/Paramaribo", label: "SRT (UTC-3)" },
  { name: "Sweden", code: "SE", tz: "Europe/Stockholm", label: "CET/CEST (UTC+1/+2)" },
  { name: "Switzerland", code: "CH", tz: "Europe/Zurich", label: "CET/CEST (UTC+1/+2)" },
  { name: "Syria", code: "SY", tz: "Asia/Damascus", label: "AST (UTC+3)" },
  { name: "Taiwan", code: "TW", tz: "Asia/Taipei", label: "CST (UTC+8)" },
  { name: "Tajikistan", code: "TJ", tz: "Asia/Dushanbe", label: "TJT (UTC+5)" },
  { name: "Tanzania", code: "TZ", tz: "Africa/Dar_es_Salaam", label: "EAT (UTC+3)" },
  { name: "Thailand", code: "TH", tz: "Asia/Bangkok", label: "ICT (UTC+7)" },
  { name: "Timor-Leste", code: "TL", tz: "Asia/Dili", label: "TLT (UTC+9)" },
  { name: "Togo", code: "TG", tz: "Africa/Lome", label: "GMT (UTC+0)" },
  { name: "Tonga", code: "TO", tz: "Pacific/Tongatapu", label: "TOT (UTC+13)" },
  { name: "Trinidad and Tobago", code: "TT", tz: "America/Port_of_Spain", label: "AST (UTC-4)" },
  { name: "Tunisia", code: "TN", tz: "Africa/Tunis", label: "CET (UTC+1)" },
  { name: "Turkey", code: "TR", tz: "Europe/Istanbul", label: "TRT (UTC+3)" },
  { name: "Turkmenistan", code: "TM", tz: "Asia/Ashgabat", label: "TMT (UTC+5)" },
  { name: "Turks and Caicos Islands", code: "TC", tz: "America/Grand_Turk", label: "EST/EDT (UTC-5/-4)" },
  { name: "Tuvalu", code: "TV", tz: "Pacific/Funafuti", label: "TVT (UTC+12)" },
  { name: "U.S. Virgin Islands", code: "VI", tz: "America/St_Thomas", label: "AST (UTC-4)" },
  { name: "Uganda", code: "UG", tz: "Africa/Kampala", label: "EAT (UTC+3)" },
  { name: "Ukraine", code: "UA", tz: "Europe/Kyiv", label: "EET/EEST (UTC+2/+3)" },
  { name: "United Arab Emirates", code: "AE", tz: "Asia/Dubai", label: "GST (UTC+4)" },
  { name: "United Kingdom", code: "GB", tz: "Europe/London", label: "BST/GMT (UTC+1/+0)" },
  { name: "United States", code: "US", tz: "America/New_York", label: "EDT/EST (UTC-4/-5)" },
  { name: "Uruguay", code: "UY", tz: "America/Montevideo", label: "UYT (UTC-3)" },
  { name: "Uzbekistan", code: "UZ", tz: "Asia/Tashkent", label: "UZT (UTC+5)" },
  { name: "Vanuatu", code: "VU", tz: "Pacific/Efate", label: "VUT (UTC+11)" },
  { name: "Vatican City", code: "VA", tz: "Europe/Vatican", label: "CET/CEST (UTC+1/+2)" },
  { name: "Venezuela", code: "VE", tz: "America/Caracas", label: "VET (UTC-4)" },
  { name: "Vietnam", code: "VN", tz: "Asia/Ho_Chi_Minh", label: "ICT (UTC+7)" },
  { name: "Wallis and Futuna", code: "WF", tz: "Pacific/Wallis", label: "WFT (UTC+12)" },
  { name: "Yemen", code: "YE", tz: "Asia/Aden", label: "AST (UTC+3)" },
  { name: "Zambia", code: "ZM", tz: "Africa/Lusaka", label: "CAT (UTC+2)" },
  { name: "Zimbabwe", code: "ZW", tz: "Africa/Harare", label: "CAT (UTC+2)" }
];

// Map lookup by country name (case-insensitive)
const COUNTRY_BY_NAME = {};
ALL_COUNTRIES.forEach(c => {
  COUNTRY_BY_NAME[c.name.toLowerCase()] = c;
});

function getCountryDetails(countryName) {
  if (!countryName) return null;
  return COUNTRY_BY_NAME[countryName.trim().toLowerCase()] || null;
}

module.exports = {
  ALL_COUNTRIES,
  COUNTRY_BY_NAME,
  getCountryDetails
};
